config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  # resources :users, only: :show do
  resources :profiles
  # end
 get 'my-trips', to: 'trips#my_trips'
 
  resources :trips, only: [:index, :show, :new, :create, :edit, :update] do
  #     # Nested the bookings now before the controller because the two routes are linked. A booking is created after trip.
    resources :bookings, only: [:index, :new, :create, :show, :destroy]
  end

  resources :bookings do
    resources :reviews, only: [:create, :destroy]
  end
  resources :trips, only: :destroy
  resources :chatrooms, only: :show do
    resources :messages, only: :create
  end
end

app/models/trip.rb
class Trip < ApplicationRecord
  belongs_to :user
  belongs_to :category
  has_many :bookings, dependent: :destroy
  has_one_attached :photo
  validates :start_date, :end_date, presence: true
  validates :name, presence: true
  validates :address, :description, :capacity, :difficulty, presence: true
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

# customise validation
  validate :validate_photo, on: :create

  def validate_photo
    return if photo.attached?
    errors.add(:photo, "must be attached")
  end

  def shortened_description
    return description if description.length < 90
    without_last_word = description[0..90].match(/(.+) \S+$/)
    if without_last_word
      without_last_word[1] + '...'
    else
      description[0..90] + '...'
    end
  end
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  def index
    @trips = policy_scope(Trip)
    @trips = @trips.near(params[:query], 300) if params[:query].present?

    # @trips = @trips.near(params[:query], 10) the 10 is km
    # The `geocoded` scope filters only trips with coordinates
    @markers = @trips.geocoded.map do |trip|
      {
        lat: trip.latitude,
        lng: trip.longitude,
        info_window: render_to_string(partial: "info_window", locals: { trip: trip }),
        image_url: helpers.asset_url("person-hiking-solid.svg")
      }
    end
  end

  def show
    @trip = Trip.find(params[:id])
    authorize @trip
    @markers = [{
      lat: @trip.latitude,
      lng: @trip.longitude,
      info_window: render_to_string(partial: "info_window", locals: { trip: @trip }),
      image_url: helpers.asset_url("person-hiking-solid.svg")
    }]
    @chatroom = Booking.where(trip: @trip).first&.chatroom
    @booking = Booking.new  # to be able to avoid the "new" view with a form
  end

  def new
    @trip = Trip.new
    authorize @trip
  end

  def create
    @trip = Trip.new(trip_params)
    @trip.user = current_user
    authorize @trip
    if @trip.save
      redirect_to trip_path(@trip)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @trip = Trip.find(params[:id])
    authorize @trip
  end

  def update
    @trip = Trip.find(params[:id])
    authorize @trip
    @trip.update(trip_params)
    redirect_to trip_path(@trip)
  end

  def destroy
    @trip = Trip.find(params[:id])
    authorize @trip
    @trip.destroy!
    redirect_to trips_path, status: :see_other
  end

  def my_trips
    authorize Trip
    TripPolicy::Scope.new(current_user, Trip).resolve_my_trips
    @trips = Trip.where(user: current_user)
  end

  private

  def trip_params
    params.require(:trip).permit(:name, :description, :address, :capacity, :difficulty, :photo, :start_date, :end_date, :price_cents, :category_id)
  end
end

app/views/trips/_form.html.erb
<%= simple_form_for(@trip) do |f| %>

  <%= f.input :name, input_html: { required: true }, input_html: {class: "trip-form-rest"}%>
  <%= f.input :description, label: 'Add some description of the trip!', input_html: {class: "trip-form-rest"}%>
  <%= f.input :address, label: "Address (starting location)", input_html: {class: "trip-form-rest"}%>
    <div class="trip-form-elements">
      <%= f.input :capacity, collection: (1..4), input_html: {class: "trip-elements-3"}%>
      <%= f.input :difficulty, collection: %w[Easy Medium Hard], input_html: {class: "trip-elements-3"}%>
      <%= f.association :category, input_html: {class: "trip-elements-3"}%>
    </div>
  <%= f.input :photo, as: :file, input_html: {class: "trip-form-rest"}, input_html: { required: true }%>
    <div class="trip-form-elements">
      <%= f.input :start_date, as: :string, required: false, input_html: {class: "datepicker", id: "range_start"} %>
      <%= f.input :end_date, as: :string, required: false, input_html: {class: "datepicker", id: "range_end"} %>
    </div>
  <%= f.input :price_cents, label: 'Estimated Transportation Costs', input_html: {class: "trip-form-rest"}%>
  <%= f.submit class: "btn btn-success" %>
<% end %>

app/views/trips/_index_card_difficulty.html.erb
<% if trip.difficulty == "Easy" %>
  <div><%= image_tag "low.png", class: "difficulty" %>
  <p class= "hover-text" style="color: green">easy</p></div>
<% elsif trip.difficulty == "Medium" %>
  <div><%= image_tag "medium.png", class: "difficulty" %>
  <p class= "hover-text" style="color: orange">medium</p></div>
<% elsif trip.difficulty == "Hard" %>
  <div><%= image_tag "hard.png", class: "difficulty" %>
    <p class= "hover-text" style="color: red">hard!</p></div>
<% end %>

app/views/trips/_info_window.html.erb
 <h3><%= trip.name %></h3>
 <p><%= trip.address %></p>

app/views/trips/_trip_index_card.html.erb
<div class="card-trip-index">
  <div class="card-trip-index-header">
    <div>
      <%if trip.photo.attached?%>
        <%= link_to cl_image_tag(trip.photo.key), trip_path(trip.id), height: 200, width: 300, crop: :fill, class: "card-img-top" %>
      <%end %>
    </div>
     <div>
      <% if trip.capacity == trip.bookings.count %>
        <span class="tag-trip-category tag-booked">FULLY BOOKED!</span>
      <% end %>
    </div>
  </div>
  <div class="card-trip-index-body">
    <div class = "d-flex justify-content-between w-100">
        <div>
          <span class="tag-trip-category <%= category_tag(trip.category) %>"><%= trip.category.name %></span>
        </div>

        <%= render "trip_index_card_difficulty", trip: trip %>

    </div>

    <div>
      <small>Date: <%= trip.start_date.strftime("%m/%d/%Y") %> - </small>
      <small><%= trip.end_date.strftime("%m/%d/%Y") %></small>
      <br>
    </div>
    <h4>
      <%= link_to trip.name, trip_path(trip.id) %>
    </h4>
    <p>
      <%= trip.shortened_description %>
    </p>

  </div>
  <div class="user-trip-index">
  <%# <img src="https://studyinbaltics.ee/wp-content/uploads/2020/03/3799Ffxy.jpg" alt="user" /> %>
    <% if trip.user.profile.profile_photo.attached? %>
      <%= cl_image_tag trip.user.profile.profile_photo.key, class: "avatar dropdown-toggle", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
    <% else %>
      <%= image_tag "https://www.slotcharter.net/wp-content/uploads/2020/02/no-avatar.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
    <% end %>
        <%# <%= cl_image_tag trip.user.profile.profile_photo.key, class: "user-trip-index-img" %>
    <div class="user-index-info">
      <h5><%= link_to trip.user.profile.username, profile_path(trip.user.profile) %></h5>
      <small style="padding: 0;  font-style: italic;">Your Local Explorer</small>
    </div>

  </div>
</div>

app/views/trips/_trip_index_card_difficulty.html.erb
<% if trip.difficulty == "Easy" %>
  <div><%= image_tag "low.png", class: "difficulty" %>
  <p class= "hover-text" style="color: green">easy</p></div>
<% elsif trip.difficulty == "Medium" %>
  <div><%= image_tag "medium.png", class: "difficulty" %>
  <p class= "hover-text" style="color: orange">medium</p></div>
<% elsif trip.difficulty == "Hard" %>
  <div><%= image_tag "hard.png", class: "difficulty" %>
    <p class= "hover-text" style="color: red">hard!</p></div>
<% end %>

app/views/trips/edit.html.erb
<div class="trip-new-container">
<h4>Edit your trip!</h4>
  <div class="trip-new-card">
    <%= render "form" %>
  </div>
</div>

app/views/trips/index.html.erb
<div class="container-trip-index">
  <div style="width: 60%;">
    <div class="container-search-bar-trip-index">
      <h2></h2>
      <%= form_with url: trips_path, method: :get, class: "d-flex search-bar-trip-index" do %>
      <%= text_field_tag :query,
      params[:query],
      class: "form-control",
      placeholder: "Find a destination"%>
        <%= submit_tag "Search", class: "btn btn-success rounded-1" %>
       <% end %>
    </div>
    <div class="container-trip-index-cards">
          <% if current_user.profile != nil %>
           <% @trips.each do |trip|  %>
           <%= render "trip_index_card", trip: trip %>
          <%end %>
        <%end%>
      </div>
  </div>


  <div class ="map-container-trips-index">
    <div style="width: 100%; height: 95vh;"
    data-controller="map"
    data-map-markers-value="<%= @markers.to_json %>"
    data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>
  </div>
  <% if  current_user.profile != nil%>
    <div class="btn btn-success float-button">
      <%= link_to " + Create a trip", new_trip_path %>
    </div>
  <% else %>
     <%= link_to "Add Profile to create a trip", new_profile_path, :class => "btn btn-success float-button" %>
  <% end %>

</div>

app/views/trips/my_trips.html.erb
<div class="body-overall-container">
    <div class="heading-my-trips">
        <h2>My Trips</h2>
    </div>
    <div class="container-trip-index-cards-mytrips">
        <% if current_user.profile != nil %>
            <% current_user.trips.each do |trip|  %>
                <%= render "trip_index_card", trip: trip %>
            <%end %>
        <%end%>
    </div>
</div>

app/views/trips/new.html.erb
<div class="trip-new-container">
<h4>Create your new trip, explorer!</h4>
  <div class="trip-new-card">
    <%= render "form" %>
  </div>
</div>

app/views/trips/show.html.erb
<div class="overall-container-tripshow">

<div class="card-profiles-showtrip">
    <div class="card-profiles-info-showtrip">
      <div class="grid-mates-showtrip">
      <p>Your Local Explorer</p>
        <% if @trip.user.profile.profile_photo.attached? %>
          <%= link_to profile_path(@trip.user.profile.id) do %>
            <%= cl_image_tag @trip.user.profile.profile_photo.key, class: "avatar-tripshow" %>
          <% end %>
        <% else %>
          <%= link_to profile_path(@trip.user.profile.id) do %>
            <%= image_tag "https://www.slotcharter.net/wp-content/uploads/2020/02/no-avatar.png", class: "avatar-tripshow" %>
          <% end %>
        <% end %>
      <% if @trip.bookings.exists? %>
      <p>Your Tripmates</p>
          <% @trip.bookings.map {|b|b.user}.map {|u| u.profile}.each do |profile|%>
            <% if profile.profile_photo.attached? %>
                <%= link_to profile_path(profile) do %>
                  <%= cl_image_tag profile.profile_photo.key, class: "avatar-tripshow" %>
                <% end %>
              <% else %>
                <%= link_to profile_path(profile) do %>
                  <%= image_tag "https://www.slotcharter.net/wp-content/uploads/2020/02/no-avatar.png", class: "avatar-tripshow" %>
                <% end %>
              <% end %>
          <% end %>
          </div>
          <% end %>
      </div>
      <br>
    <% if @trip.user == current_user && @chatroom %>
      <%= link_to 'Open Chat', chatroom_path(@chatroom), :class => "btn btn-success" %>
    <% end %>
    </div>
<div class="container-showtrip">
  <div class="card-showtrip">
    <% if @trip.photo.attached? %>
      <%= cl_image_tag @trip.photo.key%>
    <% end %>
    <div class="card-showtrip-info">
        <h1><%= @trip.name %></h1>
         <% if current_user.profile != nil%>
              <% if current_user.id != @trip.user.id %>
                <% if @trip.bookings.map {|b| b.user_id}.exclude?(current_user.id) %>
                  <% if @trip.capacity > @trip.bookings.count %>
                    <%= simple_form_for [@trip, @booking] do |f| %>
                      <div class="form-actions-trip-show">
                        <%= f.button :submit, :value => "Join us!", :class => "btn btn-success"  %>
                      </div>
                    <% end %>
                 <% end %>
                <% end %>
              <% end %>
            <% else %>
          <%= link_to "Add Profile to book", new_profile_path, :class => "btn btn-success" %>
        <% end %>
        <div class="info">
        <p>Start Date:</p>
        <%= @trip.start_date.strftime("%d/%m/%Y")  %>
        </div>

        <div class="info">
        <p>Category:</p>
        <%= @trip.category.name %>
        </div>

           <div class="info">
        <p>End Date:</p>
        <%= @trip.end_date.strftime("%d/%m/%Y")  %>
        </div>

        <div class="info">
        <p>Difficulty:</p>
        <%= @trip.difficulty %>
        </div>

        <div class="info">
        <p>Location:</p>
        <%= @trip.address %>
        </div>

        <div class="info">
        <p>Estimated fuel price:</p>
        <%= humanized_money_with_symbol(@trip.price_cents) %>
    </div>
     </div>
     <div class="info" style="margin: 0px auto;padding: 0px 100px 0px 21px;">
        <p>Description:</p>
        <%= @trip.description %>
        </div>
        <div class="info-flex", style="display: flex; gap: 5px;">


          <% if policy(@trip).edit? %>
            <%= link_to edit_trip_path do %>
              <i class="fa-solid fa-pen-to-square"></i>
            <% end %>
          <% end %>
          <% if policy(@trip).destroy? %>
            <%= link_to trip_path(@trip), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} do %>
              <i class="fa-solid fa-trash-can"></i>
            <% end %>
          <% end %>
          <div class="btn btn-success float-button-tripshow ">
            <%= link_to trips_path do %>
              <i class="fa-solid fa-left-long"></i>
            <% end %>
          </div>
        </div>
  </div>





  <div class="map-container-showtrip">
    <div style="width: 100%; height: 400px; border-radius: 10px;"
        data-controller="map"
        data-map-markers-value="<%= @markers.to_json %>"
        data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>
  </div>

</div>











 </div>