config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  # resources :users, only: :show do
  resources :profiles
  # end
 get 'my-trips', to: 'trips#my_trips'
 
  resources :trips, only: [:index, :show, :new, :create, :edit, :update] do
  #     # Nested the bookings now before the controller because the two routes are linked. A booking is created after trip.
    resources :bookings, only: [:index, :new, :create, :show, :destroy]
  end

  resources :bookings do
    resources :reviews, only: [:create, :destroy]
  end
  resources :trips, only: :destroy
  resources :chatrooms, only: :show do
    resources :messages, only: :create
  end
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  has_one_attached :front_driver_license
  has_one_attached :back_driver_license
  has_one_attached :profile_photo
  has_many :reviews, through: :bookings
  validates :first_name, :last_name, :username, presence: true
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def show
    @profile = Profile.find(params[:id])
    @review = Review.new
    @reviews = @profile.user.received_bookings.map { |booking| booking.review }.select { |r| !r.nil?}
    @bookings = Booking.where(user: current_user ).select {|booking| @profile.user.received_bookings.include? booking}
    @booking = @bookings.last
    authorize @profile
  end

  def new
    @profile = Profile.new
    authorize @profile
  end

  def create
    @profile = Profile.new(profile_params)
    @profile.user = current_user
    authorize @profile
    @profile.save
    if @profile.save!
      redirect_to root_path
    else
      render 'new', status: :unprocessable_entity
    end
  end

  def edit
    @profile = Profile.find(params[:id])
    authorize @profile
  end

  def update
    @profile = Profile.find(params[:id])
    authorize @profile
    @profile.update(profile_params)
    redirect_to profile_path(@profile)
  end

  def destroy
    @profile = Profile.find(params[:id])
    authorize @profile
    @profile.destroy
    redirect_to root_path, status: :see_other
  end

  private

  def profile_params
    params.require(:profile).permit(:username, :first_name, :last_name, :description,
      :back_driver_license, :front_driver_license, :profile_photo)
  end
end

app/views/profiles/_profileform.html.erb
<%= simple_form_for(@profile) do |f| %>
        <%= f.input :username, input_html: {class: "profile-form-rest"} %>
        <%= f.input :first_name, input_html: {class: "profile-form-rest"} %>
        <%= f.input :last_name, input_html: {class: "profile-form-rest"} %>
        <%= f.input :description, label: "Tell us a little about yourself!", input_html: {class: "profile-form-rest"}%>
        <%= f.input :profile_photo, as: :file, input_html: {class: "profile-form-rest"} %>
        <div class="profile-form-elements">
          <%= f.input :front_driver_license, as: :file, input_html: {class: "licence-picker"} %>
          <%= f.input :back_driver_license, as: :file,input_html: {class: "licence-picker"} %>
        </div>
        <%= f.submit class: "btn btn-success" %>
  <% end %>

app/views/profiles/edit.html.erb
<div class="profile-new-container">
  <h4>Edit your profile here!</h4>
    <div class="form-new-card">
      <%= render "profileform" %>
    </div>
</div>

app/views/profiles/new.html.erb
<div class="profile-new-container">
  <h4>Add your profile information here</h4>
      <div class="form-new-card">
        <%= render "profileform" %>
      </div>
</div>

app/views/profiles/show.html.erb
<div class="body-overall-container">
  <div class="banner-none" id="banner-profile-show">
    <div class="card-profile">
        <div class="card-profile-infos w-100">
          <div class="card-profile-user">
            <%if @profile.profile_photo.attached? %>
              <%= cl_image_tag @profile.profile_photo.key, class: "avatar-profile-show"%>
              <% else %>
              <%= image_tag "https://www.slotcharter.net/wp-content/uploads/2020/02/no-avatar.png", class: "avatar-profile-show"%>
            <% end %>
            <div class="card-profile-fullname">
              <h2><%= @profile.username %></h2>
              <h5><%= @profile.first_name %> <%  %> <%= @profile.last_name%></h5>
              <%if @profile.front_driver_license.attached? && @profile.back_driver_license.attached? %>
                <p>Driver license is verified</p>
              <% else %>
                <p>Driver license is not verified</p>
              <% end %>
            </div>
          </div>

          <p><%= @profile.description %></p>
        </div>
    </div>

    <br>

    <div class="container-profile-comment">
      <div>
        <h5>Reviews: </h5>
      </div>
        <% if @profile.user.received_bookings.map { |booking| booking.review }.select { |r| !r.nil?} == [] %>
          <p>No reviews yet</p>
        <% else %>
        <% @reviews.each do |review| %>
            <div><p><%= review.comment %><span class ="profile-show-reviews-user">   - by <%= link_to review.booking.user.profile.username, profile_path(review.booking.user.profile.id) %></span></p></div>
          <% end %>
        <% end %>
      </div>

        <% if @booking && current_user != @profile.user %>
          <div class="container-profile-comment-input">
            <%= simple_form_for([@booking, @review]) do |f| %>
            <%= f.input :comment, label: "Leave your comment here:", input_html: {class: "comment-imput-field"} %>
            <%= f.button :submit, class: "btn btn-success" %>
        <% end %>
        </div>
        <% end %>


    <%# <h2><%= pluralize @booking.user.profile.reviews.size, "review" %></h2>



    <% if current_user == @profile.user %>
      <div class="card-profile-tabs">
        <div class="profile-wrap">
          <% if policy(@profile).edit? %>
          <%= link_to "Update profile", edit_profile_path, class: "btn btn-success" %>
          <% end %>
        </div>

        <div class="profile-wrap">
          <% if policy(@profile).destroy? %>
          <%= link_to "Delete profile", profile_path(@profile), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "btn btn-success"%>
          <% end %>
        </div>

        <div class="profile-wrap">
          <% if policy(@profile).destroy? %>
          <%= link_to "Create a trip", new_trip_path, class: "btn btn-success"%>
          <% end %>
        </div>

        <div class="profile-wrap">
          <% if policy(@profile).destroy? %>
          <%= link_to "View the trips", trips_path, class: "btn btn-success" %>
          <% end %>
        </div>

        <div class="profile-wrap">
          <% if policy(@profile).destroy? %>
          <%= link_to "View my trips", trips_path(Trip.where("user_id = :query", query: current_user.id)), class: "btn btn-success"%>
          <% end %>
        </div>

        <div class="profile-wrap">
          <% if policy(@profile).destroy? %>
          <%= link_to 'My Bookings', bookings_path(@booking), class: "btn btn-success" %>
          <% end %>
        <div>
      </div>
    <% end %>
    <div class="btn btn-success float-button1">
      <%= link_to " + Create a trip", new_trip_path %>
    </div>
    <div class="btn btn-success float-button">
      <%= link_to "Back to trips", trips_path %>
    </div>
  </div>
</div>