config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  # resources :users, only: :show do
  resources :profiles
  # end
 get 'my-trips', to: 'trips#my_trips'
 
  resources :trips, only: [:index, :show, :new, :create, :edit, :update] do
  #     # Nested the bookings now before the controller because the two routes are linked. A booking is created after trip.
    resources :bookings, only: [:index, :new, :create, :show, :destroy]
  end

  resources :bookings do
    resources :reviews, only: [:create, :destroy]
  end
  resources :trips, only: :destroy
  resources :chatrooms, only: :show do
    resources :messages, only: :create
  end
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :trip
  belongs_to :user
  belongs_to :chatroom
  has_one :review, dependent: :destroy
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    @bookings = policy_scope(Booking)
    @chatroom = Chatroom.new

  end
  def new
    @booking = Booking.new
    @trip = Trip.find(params[:trip_id])
    authorize @booking
  end

  def create
    @trip = Trip.find(params[:trip_id])
    @booking = Booking.new
    @booking.trip = @trip
    @booking.user = current_user
    authorize @booking
    bookings_with_chat = @trip.bookings.reject do |booking|
      booking.chatroom.nil?
    end
    if bookings_with_chat.empty?
      @chatroom = Chatroom.create ### TODO make sure not to have extra chatrooms
    else
      @chatroom = bookings_with_chat.first.chatroom
    end
    @booking.chatroom = @chatroom
    if @booking.save!
      redirect_to trip_booking_path(@trip, @booking)
    else
      render 'new', status: :unprocessable_entity
    end
  end

  def show
    @booking = Booking.find(params[:id])
    @chatroom = @booking.chatroom
    authorize @booking

  end

  def destroy
    @booking = Booking.find(params[:id])
    authorize @booking
    @booking.delete
    redirect_to bookings_path(@booking), status: :see_other
  end
end

app/views/bookings/index.html.erb
<div class="body-overall-container" style="margin: 0; padding: 75px;">
  <h1 id="bookings-index-title">Your Bookings</h1>
    <div class="bookings-index-container">
      <% @bookings.each do |booking|  %>
      <div class="bookings-index-cards">
      <div class="booking-index-info">
        <h4><%= link_to booking.trip.name, trip_path(booking.trip.id)%></h4>
        <p><%= booking.trip.start_date.to_date %> to <%= booking.trip.end_date.to_date %></p>
      </div>
      <div id="explorer-title-index-bookings"> <p>Your Explorer</p></div>
  <div class="explorer-card-bookings-index">
                  <% if booking.trip.user.profile.profile_photo.attached? %>
                    <%= cl_image_tag booking.trip.user.profile.profile_photo.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
                      <% else %>
                    <%= image_tag "https://www.slotcharter.net/wp-content/uploads/2020/02/no-avatar.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
                  <% end %>
                  <%= link_to booking.trip.user.profile.username, profile_path(booking.trip.user.profile.id) %>
                </div>
        <br>
        <div class="bookings-index-links">
          <%# <%= link_to "Review on Explorer", profile_path(booking.trip.user.profile)%>
          <%= link_to "More info", booking_path(booking)%>
          <%= link_to 'Open chat', chatroom_path(booking.chatroom), :class => "btn btn-primary"%>
          </div>
      </div>
      <%end %>
    </div>
  </div>

app/views/bookings/show.html.erb
<div class="body-overall-container">
  <div class="booking-show-container">
    <h1 id="booking-show-title">Congratulations! You just booked this trip!</h1>
      <div class="booking-show-card">
          <% if @booking.trip.photo.attached? %>
            <%= cl_image_tag @booking.trip.photo.key%>
          <% end %>
          <div class="d-flex justify-content-between mx-5">
            <div class="card-showbooking-info">
              <h2><%= @booking.trip.name %></h2>
              <div id="dates-booking-show">
                  <p>starting date: <%= @booking.trip.start_date.to_date.strftime("%d/%m/%Y") %></p>
                  <p>ending date: <%= @booking.trip.end_date.to_date.strftime("%d/%m/%Y") %></p>
              </div>
            </div>
            <div id="explorer-card-bookings-show-flex">
                <p>Your Local Exporer</p>
                <div class="explorer-card-bookings-show">
                  <% if @booking.trip.user.profile.profile_photo.attached? %>
                    <%= cl_image_tag @booking.trip.user.profile.profile_photo.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
                      <% else %>
                    <%= image_tag "https://www.slotcharter.net/wp-content/uploads/2020/02/no-avatar.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
                  <% end %>
                  <%= link_to @booking.trip.user.profile.username, profile_path(@booking.trip.user.profile.id) %>
                </div>
            </div>
          </div>

      </div>
    <div class="booking-show-buttons-card">
      <ul class="booking-show-inline">
      <li> <%= link_to 'Discover more trips', trips_path(@trip), :class => "btn btn-success" %> </li>
      <%= link_to 'Open chat', chatroom_path(@chatroom), :class => "btn btn-success" %>
      <% if policy(@booking).destroy? %>
    <li><%= link_to "Delete booking", trip_booking_path(@booking), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, :class => "btn btn-success"%> </li>
      <% end %>
    <li><%= link_to 'Show my bookings', bookings_path(@booking), :class => "btn btn-success" %> </li>
      </ul>
    </div>
  </div>
</div>