config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  # resources :users, only: :show do
  resources :profiles
  # end
 get 'my-trips', to: 'trips#my_trips'
 
  resources :trips, only: [:index, :show, :new, :create, :edit, :update] do
  #     # Nested the bookings now before the controller because the two routes are linked. A booking is created after trip.
    resources :bookings, only: [:index, :new, :create, :show, :destroy]
  end

  resources :bookings do
    resources :reviews, only: [:create, :destroy]
  end
  resources :trips, only: :destroy
  resources :chatrooms, only: :show do
    resources :messages, only: :create
  end
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class=" navbar navbar-expand-sm navbar-light navbar-lewagon fixed-top">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <div class= "nav-logo"><%= image_tag "mountain_logo.png" %>
      </div>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#SupportedContent" aria-controls="SupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
            <% if current_user.profile != nil %>
              <%# <li class="nav-item active">
              <%= link_to "Home", "#", class: "nav-link" %>
              <%# <%# </li> %>
              <%# <li class="nav-item"> %>
              <%# <%= link_to "Messages", "#", class: "nav-link" %>
              <%# <div style="vertical-align: middle; margin-top: 12px; margin-right: 15px; color: #3a5a40"> %>
              <%# <%= current_user.profile.username %>
              <div style="vertical-align: middle; margin-top: 12px; margin-right: 15px; color: #3a5a40">
              <%= current_user.profile.username %>
              </div>
            <% end  %>
          <li class="nav-item dropdown">
            <% if current_user.profile&.profile_photo&.attached? %>
              <%= cl_image_tag current_user.profile.profile_photo.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
              <% else %>
              <%= image_tag "https://www.slotcharter.net/wp-content/uploads/2020/02/no-avatar.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% end %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <% if user_signed_in? && current_user.profile != nil %>
                <%= link_to "Profile", profile_path(current_user.profile.id), class: "dropdown-item" %>
              <% else %>
                <%= link_to "Add Profile", new_profile_path, class: "dropdown-item" %>
              <% end %>
              <%= link_to "Home", root_path, class: "dropdown-item" %>
              <%= link_to 'My Bookings', bookings_path(), class: "dropdown-item" %>
              <%= link_to "My Trips", my_trips_path, class: "dropdown-item" %>
              <%= link_to "Available trips", trips_path, class: "dropdown-item"%>
              <%= link_to "Edit account", edit_user_registration_path, class: "dropdown-item"%>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
          <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>